import React, { useState, useEffect, useRef } from 'react';
import { Save, User, Mic, MessageSquare, Plus, Trash2, Check, Sparkles, Activity, Loader2, Play, Pause } from 'lucide-react';
import { AgentConfig } from '../types';

interface AgentEditorProps {
  agents: AgentConfig[];
  loading?: boolean;
  onAddAgent: (agent: AgentConfig) => Promise<AgentConfig | null>;
  onUpdateAgent: (agent: AgentConfig) => Promise<void>;
  onDeleteAgent: (id: string) => Promise<void>;
}

const FALLBACK_VOICES = [
  // Ultravox/ElevenLabs Voices (Hardcoded fallbacks)
  { 
    id: 'ad69ddb2-363f-4279-adf4-5961f127ec2f', 
    voiceId: 'ad69ddb2-363f-4279-adf4-5961f127ec2f',
    name: 'Chinmay (English India)', 
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/xnx6sPTtvU635ocDt2j7/iWmWpwBvJNpwKr4KlYB8.mp3' 
  },
  { 
    id: 'd17917ec-fd98-4c50-8c83-052c575cbf3e', 
    voiceId: 'd17917ec-fd98-4c50-8c83-052c575cbf3e',
    name: 'Riya (English India)', 
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/wlmwDR77ptH6bKHZui0l/vDP823KvNyKcS3acBpIF.mp3'
  },
  { 
    id: '44504e63-59c5-4f69-9340-423231c79a03', 
    voiceId: '44504e63-59c5-4f69-9340-423231c79a03',
    name: 'Anika (English India)', 
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/90ipbRoKi4CpHXvKVtl0/RHjv4PzQ8pTguUk1dcO5.mp3'
  },
  {
    id: 'u7DoEF74Zzu8FP2dxDfk',
    voiceId: 'u7DoEF74Zzu8FP2dxDfk',
    name: 'Mandira (Custom)',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/u7DoEF74Zzu8FP2dxDfk/preview.mp3'
  },
  {
    id: 'terrence',
    name: 'Terrence (Legacy)',
    previewUrl: ''
  }
];

const AgentEditor: React.FC<AgentEditorProps> = ({ agents, loading, onAddAgent, onUpdateAgent, onDeleteAgent }) => {
  const [selectedAgentId, setSelectedAgentId] = useState<string | null>(agents[0]?.id || null);
  const [formData, setFormData] = useState<AgentConfig | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  
  // Voice Preview State
  const [voices, setVoices] = useState<any[]>(FALLBACK_VOICES);
  const [isVoiceDropdownOpen, setIsVoiceDropdownOpen] = useState(false);
  const [playingVoiceId, setPlayingVoiceId] = useState<string | null>(null);
  const audioRef = React.useRef<HTMLAudioElement | null>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (isVoiceDropdownOpen && !(event.target as Element).closest('.voice-dropdown-container')) {
        setIsVoiceDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isVoiceDropdownOpen]);

  // Fetch voices
  useEffect(() => {
    fetch('http://localhost:5050/voices')
        .then(res => res.json())
        .then(data => {
            if (Array.isArray(data) && data.length > 0) {
                setVoices(data);
            }
        })
        .catch(err => console.error('Failed to fetch voices:', err));
  }, []);

  const handlePlayPreview = (e: React.MouseEvent, voice: any) => {
    e.stopPropagation();
    
    if (playingVoiceId === voice.voiceId || playingVoiceId === voice.id) {
        // Stop currently playing
        if (audioRef.current) {
            audioRef.current.pause();
            audioRef.current = null;
        }
        setPlayingVoiceId(null);
        return;
    }

    // Stop existing
    if (audioRef.current) {
        audioRef.current.pause();
    }

    if (!voice.previewUrl) return;

    const audio = new Audio(voice.previewUrl);
    audio.onended = () => setPlayingVoiceId(null);
    audio.play().catch(e => console.error("Audio play failed", e));
    
    audioRef.current = audio;
    setPlayingVoiceId(voice.voiceId || voice.id);
  };

  useEffect(() => {
    if (selectedAgentId) {
      const agent = agents.find(a => a.id === selectedAgentId);
      if (agent) {
        setFormData(agent);
        setIsSaved(false);
      }
    } else if (agents.length > 0 && !selectedAgentId) {
      setSelectedAgentId(agents[0].id);
    }
  }, [selectedAgentId, agents]);

  const handleSave = async () => {
    if (!formData || isSaving) return;
    setIsSaving(true);
    try {
      await onUpdateAgent(formData);
      setIsSaved(true);
      setTimeout(() => setIsSaved(false), 2000);
    } finally {
      setIsSaving(false);
    }
  };

  const handleCreate = async () => {
    if (isSaving) return;
    const newAgent: AgentConfig = {
      id: '', // Will be generated by database
      name: 'New Agent',
      tone: 'Professional',
      script: 'You are a helpful assistant from VOCA AI.',
      voiceId: 'terrence'
    };
    setIsSaving(true);
    try {
      const created = await onAddAgent(newAgent);
      if (created) {
        setSelectedAgentId(created.id);
      }
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('Are you sure you want to delete this agent?')) {
      setIsSaving(true);
      try {
        await onDeleteAgent(id);
        if (selectedAgentId === id) {
          const remaining = agents.filter(a => a.id !== id);
          setSelectedAgentId(remaining[0]?.id || null);
        }
      } finally {
        setIsSaving(false);
      }
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="flex flex-col items-center gap-3 text-slate-400">
          <Loader2 className="w-8 h-8 animate-spin" />
          <span>Loading agents...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full max-w-7xl mx-auto p-6 gap-6">
      {/* Sidebar List */}
      <div className="w-80 bg-white rounded-2xl border border-slate-200 flex flex-col overflow-hidden shadow-sm shrink-0">
        <div className="p-5 border-b border-slate-100 flex justify-between items-center bg-slate-50">
            <h2 className="font-bold text-slate-800">Your Agents</h2>
            <button 
                onClick={handleCreate} 
                className="p-2 bg-white border border-slate-200 text-blue-600 rounded-lg hover:bg-blue-50 transition-colors shadow-sm"
                title="Create New Agent"
            >
                <Plus className="w-4 h-4" />
            </button>
        </div>
        <div className="flex-1 overflow-y-auto p-3 space-y-2">
            {agents.map(agent => (
                <div 
                    key={agent.id}
                    onClick={() => setSelectedAgentId(agent.id)}
                    className={`p-3 rounded-xl flex items-center gap-3 cursor-pointer transition-all border group relative ${
                        selectedAgentId === agent.id 
                        ? 'bg-blue-50 border-blue-200 shadow-sm' 
                        : 'hover:bg-slate-50 border-transparent'
                    }`}
                >
                    <div className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold shadow-sm ${selectedAgentId === agent.id ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-500'}`}>
                        {agent.name.charAt(0)}
                    </div>
                    <div className="flex-1 overflow-hidden">
                        <div className={`font-semibold truncate ${selectedAgentId === agent.id ? 'text-blue-900' : 'text-slate-900'}`}>{agent.name}</div>
                        <div className="text-xs text-slate-500 truncate flex items-center gap-1">
                           <span className={`w-1.5 h-1.5 rounded-full ${agent.tone === 'Friendly' ? 'bg-green-400' : agent.tone === 'Assertive' ? 'bg-red-400' : 'bg-blue-400'}`}></span>
                           {agent.tone}
                        </div>
                    </div>
                    
                    {/* Sidebar Play Button */}
                    <button
                        onClick={(e) => {
                            const agentVoice = voices.find(v => (v.voiceId || v.id) === agent.voiceId);
                            if (agentVoice) handlePlayPreview(e, agentVoice);
                        }}
                        className={`p-2 rounded-full transition-colors opacity-0 group-hover:opacity-100 focus:opacity-100 ${
                            playingVoiceId === agent.voiceId 
                            ? 'opacity-100 text-blue-600 bg-blue-100' 
                            : 'text-slate-400 hover:bg-slate-200'
                        }`}
                        title="Preview Voice"
                    >
                         {playingVoiceId === agent.voiceId ? (
                            <div className="w-3 h-3 flex items-center justify-center gap-0.5">
                                <div className="w-0.5 h-2 bg-current rounded-full animate-pulse"></div>
                                <div className="w-0.5 h-2 bg-current rounded-full animate-pulse delay-75"></div>
                                <div className="w-0.5 h-2 bg-current rounded-full animate-pulse delay-150"></div>
                            </div>
                        ) : (
                            <Play className="w-3 h-3 fill-current" />
                        )}
                    </button>
                </div>
            ))}
            {agents.length === 0 && (
                <div className="text-center py-12 px-4 text-slate-400 text-sm">
                    <Sparkles className="w-8 h-8 mx-auto mb-2 opacity-20" />
                    No agents created yet.<br/>Click + to start.
                </div>
            )}
        </div>
      </div>

      {/* Editor Pane */}
      <div className="flex-1 bg-white rounded-2xl border border-slate-200 flex flex-col shadow-sm overflow-hidden">
        {formData ? (
            <>
                <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div className="flex items-center gap-4">
                        <div className="w-14 h-14 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
                            <User className="w-7 h-7" />
                        </div>
                        <div>
                            <input 
                                type="text" 
                                value={formData.name}
                                onChange={(e) => setFormData({...formData, name: e.target.value})}
                                className="bg-transparent text-2xl font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-200 rounded px-1 -ml-1 w-full"
                                placeholder="Agent Name"
                            />
                            <div className="text-sm text-slate-500 flex items-center gap-2 mt-1">
                                <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
                                Configuration Active
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                         <button 
                            onClick={() => handleDelete(formData.id)}
                            className="p-3 text-red-400 hover:text-red-600 hover:bg-red-50 rounded-xl transition-colors"
                            title="Delete Agent"
                        >
                            <Trash2 className="w-5 h-5" />
                        </button>
                        <div className="h-8 w-px bg-slate-200 mx-1"></div>
                        <button 
                            onClick={handleSave}
                            className={`flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all transform active:scale-95 ${
                                isSaved 
                                ? 'bg-green-500 text-white shadow-green-200' 
                                : 'bg-slate-900 text-white hover:bg-slate-800 shadow-lg shadow-slate-900/20'
                            }`}
                        >
                            {isSaved ? <Check className="w-5 h-5" /> : <Save className="w-5 h-5" />}
                            {isSaved ? 'Saved' : 'Save Changes'}
                        </button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-8 space-y-8 bg-slate-50/30">
                    {/* Settings Grid */}
                    <div className="grid grid-cols-2 gap-6">
                        <div className="space-y-3">
                            <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                                <MessageSquare className="w-4 h-4 text-blue-500" /> Tone & Personality
                            </label>
                            <div className="relative">
                                <select 
                                    value={formData.tone}
                                    onChange={(e) => setFormData({...formData, tone: e.target.value as any})}
                                    className="w-full p-4 pl-4 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all appearance-none font-medium text-slate-700"
                                >
                                    <option value="Friendly">Friendly & Warm</option>
                                    <option value="Professional">Professional & Formal</option>
                                    <option value="Assertive">Assertive & Sales-driven</option>
                                </select>
                                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
                                    <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-3">
                            <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                                <Mic className="w-4 h-4 text-blue-500" /> Voice Model
                            </label>
                            <div className="relative voice-dropdown-container">
                                <div 
                                    onClick={() => setIsVoiceDropdownOpen(!isVoiceDropdownOpen)}
                                    className="w-full p-4 bg-white border border-slate-200 rounded-xl focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500 cursor-pointer flex justify-between items-center group"
                                >
                                    <div className="flex items-center gap-3 flex-1 overflow-hidden">
                                        <span className="font-medium text-slate-700 truncate">
                                            {voices.find(v => (v.voiceId || v.id) === formData.voiceId)?.name || formData.voiceId}
                                        </span>
                                        {/* Selected Voice Play Button */}
                                        <button
                                            onClick={(e) => {
                                                const selectedVoice = voices.find(v => (v.voiceId || v.id) === formData.voiceId);
                                                if (selectedVoice) handlePlayPreview(e, selectedVoice);
                                            }}
                                            className={`p-1.5 rounded-full transition-colors ${
                                                playingVoiceId === formData.voiceId 
                                                ? 'text-blue-600 bg-blue-100' 
                                                : 'text-slate-400 hover:bg-slate-100 opacity-50 group-hover:opacity-100'
                                            }`}
                                            title="Preview Selected Voice"
                                        >
                                             {playingVoiceId === formData.voiceId ? (
                                                <div className="w-3 h-3 flex items-center justify-center gap-0.5">
                                                    <div className="w-0.5 h-2 bg-current rounded-full animate-pulse"></div>
                                                    <div className="w-0.5 h-2 bg-current rounded-full animate-pulse delay-75"></div>
                                                    <div className="w-0.5 h-2 bg-current rounded-full animate-pulse delay-150"></div>
                                                </div>
                                            ) : (
                                                <Play className="w-3 h-3 fill-current" />
                                            )}
                                        </button>
                                    </div>
                                    <svg className={`w-4 h-4 text-slate-400 transition-transform ${isVoiceDropdownOpen ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                </div>
                                
                                {isVoiceDropdownOpen && (
                                    <div className="absolute z-10 w-full mt-2 bg-white border border-slate-200 rounded-xl shadow-xl max-h-60 overflow-y-auto">
                                        {voices.map(v => {
                                            const vId = v.voiceId || v.id;
                                            const isSelected = formData.voiceId === vId;
                                            const isPlaying = playingVoiceId === vId;
                                            
                                            return (
                                                <div 
                                                    key={vId}
                                                    onClick={() => {
                                                        setFormData({...formData, voiceId: vId});
                                                        setIsVoiceDropdownOpen(false);
                                                    }}
                                                    className={`p-3 flex items-center justify-between hover:bg-slate-50 cursor-pointer ${isSelected ? 'bg-blue-50 text-blue-900 font-medium' : 'text-slate-700'}`}
                                                >
                                                    <span className="truncate flex-1">{v.name}</span>
                                                    {v.previewUrl && (
                                                        <button
                                                            onClick={(e) => handlePlayPreview(e, v)}
                                                            className={`p-2 rounded-full hover:bg-slate-200 transition-colors ${isPlaying ? 'text-blue-600 bg-blue-100' : 'text-slate-400'}`}
                                                            title={isPlaying ? "Stop Preview" : "Play Preview"}
                                                        >
                                                            {isPlaying ? (
                                                                <div className="w-4 h-4 flex items-center justify-center gap-0.5">
                                                                    <div className="w-1 h-3 bg-current rounded-full animate-pulse"></div>
                                                                    <div className="w-1 h-3 bg-current rounded-full animate-pulse delay-75"></div>
                                                                    <div className="w-1 h-3 bg-current rounded-full animate-pulse delay-150"></div>
                                                                </div>
                                                            ) : (
                                                                <svg className="w-4 h-4 fill-current" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
                                                            )}
                                                        </button>
                                                    )}
                                                </div>
                                            );
                                        })}
                                    </div>
                                )}
                            </div>
                        </div>
                        <div className="space-y-3">
                            <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                                <MessageSquare className="w-4 h-4 text-blue-500" /> Language Style
                            </label>
                            <div className="relative">
                                <select 
                                    value={formData.languageStyle || 'Tanglish'}
                                    onChange={(e) => setFormData({...formData, languageStyle: e.target.value as any})}
                                    className="w-full p-4 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all appearance-none font-medium text-slate-700"
                                >
                                    <option value="Tanglish">Chennai Tanglish (Recommended)</option>
                                    <option value="Formal Tamil">Formal Tamil</option>
                                    <option value="Casual Chennai">Casual Chennai Local</option>
                                </select>
                                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none">
                                    <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                </div>
                            </div>
                        </div>
                        <div className="space-y-3">
                            <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                                <Activity className="w-4 h-4 text-blue-500" /> Speaking Speed ({formData.voiceSpeed || 1}x)
                            </label>
                            <div className="relative pt-2">
                                <input 
                                    type="range" 
                                    min="0.5" 
                                    max="1.5" 
                                    step="0.1"
                                    value={formData.voiceSpeed || 1}
                                    onChange={(e) => setFormData({...formData, voiceSpeed: parseFloat(e.target.value)})}
                                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                                />
                                <div className="flex justify-between text-xs text-slate-400 mt-2 font-mono">
                                    <span>Slow (0.5x)</span>
                                    <span>Normal (1.0x)</span>
                                    <span>Fast (1.5x)</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Script Editor */}
                    <div className="flex-1 flex flex-col h-full min-h-[400px]">
                        <div className="flex justify-between items-center mb-3">
                            <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                                <Sparkles className="w-4 h-4 text-purple-500" /> System Prompt / Script
                            </label>
                            <span className="text-xs font-medium text-slate-400 bg-slate-100 px-2 py-1 rounded">Markdown Supported</span>
                        </div>
                        <div className="flex-1 relative group rounded-2xl shadow-sm border border-slate-200 bg-white overflow-hidden focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500 transition-all">
                            <textarea 
                                value={formData.script}
                                onChange={(e) => setFormData({...formData, script: e.target.value})}
                                className="w-full h-full p-6 bg-transparent border-none outline-none resize-none font-mono text-sm leading-relaxed text-slate-700"
                                placeholder="Enter the system instructions here. Define the agent's persona, goals, and handling of objections..."
                            />
                            <div className="absolute bottom-4 right-4 text-xs font-mono text-slate-400 bg-slate-50 border border-slate-100 px-2 py-1 rounded-md pointer-events-none">
                                {formData.script.length} chars
                            </div>
                        </div>
                        <p className="text-xs text-slate-500 mt-3">
                            <strong>Pro Tip:</strong> Be specific about how the agent should introduce themselves and handle key objections. 
                            Use variables like <code className="bg-slate-100 px-1 py-0.5 rounded text-blue-600">{"{customer_name}"}</code> or <code className="bg-slate-100 px-1 py-0.5 rounded text-blue-600">{"{business_name}"}</code> to make it dynamic.
                        </p>
                    </div>
                    </div>
            </>
        ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-400 bg-slate-50/30">
                <div className="w-20 h-20 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                    <User className="w-10 h-10 text-slate-300" />
                </div>
                <h3 className="text-lg font-semibold text-slate-600">No Agent Selected</h3>
                <p>Select an agent from the list or create a new one to start editing.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default AgentEditor;